name: ml
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python==3.7
  - cython
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - seaborn
  - numpy
  - pandas  
  - requests
  - rise
  - pip:
    - git+https://github.com/scikit-learn/scikit-learn # Get dev version that works with Python 3.7
    - dtreeviz
 

    
